/*
 * Name: <YOUR NAME>
 * Admin No: 241036U
 * Tutorial Group: <TUTORIAL GROUP>
 */

// <auto-generated />
using ArcaneVault.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArcaneVault.Api.Migrations
{
    [DbContext(typeof(ArcaneVaultDbContext))]
    partial class ArcaneVaultDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("ArcaneVault.Api.Data.Entities.ArcaneVaultUser", b =>
                {
                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserName");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("ArcaneVaultUsers");
                });

            modelBuilder.Entity("ArcaneVault.Api.Data.Entities.ArcaneVaultUserRole", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("RoleId");

                    b.ToTable("ArcaneVaultUserRoles");
                });

            modelBuilder.Entity("ArcaneVault.Api.Data.Entities.Category", b =>
                {
                    b.Property<string>("CategoryCode")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryCode");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("ArcaneVault.Api.Data.Entities.CollectionItem", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("StartingQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("ItemId");

                    b.HasIndex("UserName");

                    b.ToTable("CollectionItems");
                });

            modelBuilder.Entity("ArcaneVault.Api.Data.Entities.CollectionItemCategory", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryCode")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("ItemId", "CategoryCode");

                    b.HasIndex("CategoryCode");

                    b.ToTable("CollectionItemCategories");
                });

            modelBuilder.Entity("ArcaneVault.Api.Data.Entities.ArcaneVaultUser", b =>
                {
                    b.HasOne("ArcaneVault.Api.Data.Entities.ArcaneVaultUserRole", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ArcaneVault.Api.Data.Entities.CollectionItem", b =>
                {
                    b.HasOne("ArcaneVault.Api.Data.Entities.ArcaneVaultUser", "User")
                        .WithMany("CollectionItems")
                        .HasForeignKey("UserName")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ArcaneVault.Api.Data.Entities.CollectionItemCategory", b =>
                {
                    b.HasOne("ArcaneVault.Api.Data.Entities.Category", "Category")
                        .WithMany("ItemCategories")
                        .HasForeignKey("CategoryCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArcaneVault.Api.Data.Entities.CollectionItem", "Item")
                        .WithMany("ItemCategories")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("ArcaneVault.Api.Data.Entities.ArcaneVaultUser", b =>
                {
                    b.Navigation("CollectionItems");
                });

            modelBuilder.Entity("ArcaneVault.Api.Data.Entities.ArcaneVaultUserRole", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ArcaneVault.Api.Data.Entities.Category", b =>
                {
                    b.Navigation("ItemCategories");
                });

            modelBuilder.Entity("ArcaneVault.Api.Data.Entities.CollectionItem", b =>
                {
                    b.Navigation("ItemCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
